# Generated by Django 3.0 on 2020-01-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200131_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('Description', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Indoor', 'Indoor'), ('outdoor', 'outdoor'), ('anywhere', 'anywhere')], max_length=100, null=True)),
            ],
        ),
    ]
