# Generated by Django 3.0.2 on 2020-02-11 09:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('UI', 'UI'), ('Rest Api', 'REST API')], max_length=100)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('Narayana', 'NARAYANA'), ('Srinivas', 'SRINIVAS'), ('Mohan Reddy', 'MOHAN REDDY'), ('Wilson', 'WILSON')], max_length=100)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'MORNING'), ('Evening', 'EVENINg'), ('Night', 'NIGHT')], max_length=100)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Ameerpet', 'AMEERPET'), ('Madhapur', 'MADHAPUR'), ('Kphb', 'KPHB'), ('Uppal', 'UPPAL')], max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
