# Generated by Django 3.0.2 on 2020-03-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multilevelapp.Emp')),
                ('cname', models.CharField(max_length=100)),
                ('sales', models.IntegerField()),
            ],
            bases=('multilevelapp.emp',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multilevelapp.Customer')),
                ('sname', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
            bases=('multilevelapp.customer',),
        ),
    ]
